---
title: "gradientSimilarityAnalysis"
author: "MR"
date: "02/08/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library("tidyverse")
library("ggplot2")
library("R.matlab")
library("plyr")
library("dplyr")
library("broom")
library("effectsize")
library("car")
library("fmsb")
library("scatterplot3d") 
library("ggridges")
library("ggpubr")
library("lme4")
library("viridis")
library("plot3D")
library("rgl")
library("mgcv")
library("grid") 



gradientdata <- readMat("C:\\Users\\Magda\\Documents\\Matlab\\rgs\\n370\\allgradients_n370.mat")
alldata <- readMat("C:\\Users\\Magda\\Documents\\Matlab\\rgs\\n370\\mvrData.mat")
mediandata <- readMat("C:\\Users\\Magda\\Documents\\Matlab\\rgs\\n370\\mediandata.mat")


```

### Boxplots in Figure 3 B and D 

```{r boxplot, echo=FALSE}

roinetworks <- readMat("C:\\Users\\Magda\\Documents\\Matlab\\rgs\\n370\\roinetworks_lhrh.mat")
roinetworks <- t(data.frame(roinetworks))
roilabels <- unique(roinetworks)
list_gNwMedian <- list()
gNwMedian <- data.frame(matrix(, nrow=7, ncol=370))


for (g in 1:3) {
  thisGradient<- data.frame(gradientdata$g.aligned.all[,,g])
  thisGradient <- thisGradient %>% mutate_if(is.character,as.numeric)
  thisGradient<-data.frame(t(thisGradient),roinetworks)

  
  for (n in 1:7) {
     gNwMedian[n,] <- thisGradient %>% filter(thisGradient[,371]==roilabels[n]) %>%  dplyr::summarise(across(where(is.numeric), ~ median(.x, na.rm = TRUE)))
  }
    list_gNwMedian[[g]] <- gNwMedian

}


#focus on first gradient
gradientToPlot <- data.frame(t(list_gNwMedian[[1]]))
names(gradientToPlot) <- c(roilabels)
gradientToPlot <- gradientToPlot[ , order(names(gradientToPlot))]


#add in questionnaire data
alldata <- data.frame(alldata)
names(alldata) <- c('subjectID', 'gender', 'age', 'AQtotal', 'AQsocial', 'AQswitch', 'AQdetail', 'AQcomm', 'AQimag', 'GSQtotal', 'simGradient1', 'simGradient2', 'simGradient3')


gradientToPlot <- data.frame(gradientToPlot, alldata)


gradientToPlotLong <- gradientToPlot %>%  pivot_longer(cols = Cont:Vis, names_to = "network", values_to = "median_gscore")


#terciles
lowaq_cutoff <- quantile(gradientToPlot$AQtotal, 1/3) 
highaq_cutoff <- quantile(gradientToPlot$AQtotal, 2/3) 

lowgsq_cutoff <- quantile(gradientToPlot$GSQtotal, 1/3) 
highgsq_cutoff <- quantile(gradientToPlot$GSQtotal, 2/3) 



#by group
gradientToPlotLong <- gradientToPlotLong %>% 
  mutate(aqgroup = case_when(AQtotal > highaq_cutoff ~ "high",
                             AQtotal >= lowaq_cutoff & AQtotal <= highaq_cutoff  ~ "mid",
                        AQtotal < lowaq_cutoff  ~ "low"))

gradientToPlotLong <- gradientToPlotLong %>% 
  mutate(gsqgroup = case_when(GSQtotal > highgsq_cutoff ~ "high",
                              GSQtotal >= lowgsq_cutoff & GSQtotal <= highgsq_cutoff  ~ "mid",
                        GSQtotal < lowgsq_cutoff  ~ "low"))




p <- ggplot(data=subset(gradientToPlotLong, !is.na(gsqgroup)), aes(x=factor(gsqgroup), y=median_gscore, fill=factor(gsqgroup))) + 
  geom_boxplot(width=0.3) +
  facet_grid(factor(network, levels=c('Vis', 'SomMot', 'DorsAttn', 'SalVentAttn', 'Cont', 'Limbic', 'Default'))~.,switch = "y")+
  scale_y_continuous(limits = c(-3,2))+
  labs(x="", y = "Median gradient score")+
  #scale_x_discrete(labels = NULL, breaks = NULL)+
  theme(axis.text.y=element_blank(),axis.ticks.y=element_blank(), strip.text.y.left = element_text(angle = 0))+
  coord_flip()+
  #scale_fill_manual(name = "", labels = c("High GSQ", "Mid GSQ", "Low GSQ"),
  scale_fill_manual(name = "", labels = c("High AQ  ", "Mid AQ  ", "Low AQ  "),
  values=c("#ef8a62","#af8dc3","#67a9cf"))
 
# Generate the ggplot2 plot grob
g <- grid.force(ggplotGrob(p))
# Get the names of grobs and their gPaths into a data.frame structure
grobs_df <- do.call(cbind.data.frame, grid.ls(g, print = FALSE))
# Build optimal gPaths that will be later used to identify grobs and edit them
grobs_df$gPath_full <- paste(grobs_df$gPath, grobs_df$name, sep = "::")
grobs_df$gPath_full <- gsub(pattern = "layout::", 
                            replacement = "", 
                            x = grobs_df$gPath_full, 
                            fixed = TRUE)

# Get the gPaths of the strip background grobs
strip_bg_gpath <- grobs_df$gPath_full[grepl(pattern = ".*strip\\.background.*", 
                                            x = grobs_df$gPath_full)]

fills=c("#8DA0CB", "#66C2A5", "#e78ac3", "#e5c494", "#A6D854", "#fc8d62", "#FFD92F")

# Edit the grobs
for (i in 1:length(strip_bg_gpath)){
  g <- editGrob(grob = g, gPath = strip_bg_gpath[i], gp = gpar(fill = fills[i]))
  #g <- editGrob(grob = g, gPath = strip_txt_gpath[i], gp = gpar(col = txt_colors[i]))
}

# Draw the edited plot
grid.newpage(); grid.draw(g)



```

### Multivariate similarity analysis

```{r regression, echo=FALSE}


mod0<-lm(cbind(simGradient1, simGradient2, simGradient3) ~ age + gender + AQtotal + GSQtotal, data=alldata)
summary(mod0)


mod1<-lm(cbind(simGradient1, simGradient2, simGradient3) ~ age + gender + AQsocial + AQswitch + AQdetail + AQcomm + AQimag + GSQtotal, data=alldata)
summary(mod1)


fit<-lm(cbind(simGradient1, simGradient2, simGradient3) ~ age + gender + AQtotal + GSQtotal, data=alldata)
summary(fit)

#plot(alldata$AQdetail,alldata$simGradient3)
#abline(lm(simGradient3~AQdetail, data=alldata))


# type I SS, the restricted model in a regression analysis for your first predictor c is the null-model which only uses the absolute term
summary(manova(mod1)) #Pillai's trace sig for AQdetail, trending for AQimag

#type II SS, the unrestricted model in a regression analysis for your first predictor c is the full model which includes all predictors except for their interaction
Manova(mod1, type="III") #Pillai's trace sig for AQdetail, trending for AQimag

fit<-lm(simGradient1 ~ age + gender + AQsocial + AQswitch + AQdetail + AQcomm + AQimag + GSQtotal, data=alldata)

fit<-lm(simGradient2 ~ age + gender + AQsocial + AQswitch + AQdetail + AQcomm + AQimag + GSQtotal, data=alldata)

fit<-lm(simGradient3 ~ age + gender + AQsocial + AQswitch + AQdetail + AQcomm + AQimag + GSQtotal, data=alldata)


summary(fit)
# Pillai's trace sig for AQdetail -> parameter estimates for these multivariate effects linked to AQdetail for grad 1:3 -> association where error bars do not overlap with zeroconfint(fit, 'body.weight', level=0.95)

confint(fit, 'AQdetail', level=0.9)

vif(fit) # variance inflation factor (multicollinearity metric 1)
#what percentage the variance (i.e. the standard error squared) is inflated for each coefficient. For example, a VIF of 1.9 tells you that the variance of a particular coefficient is 90% bigger than what you would expect if there was no multicollinearity 
#-> for each simGradient individually are all under 2 (some researchers suggest 2.5 as threshold)
1/vif(fit) # tolerance (multicollinearity metric 2)
#If n <600,tolerance should exceed 0.3



```

### Multiple regression model comparison – effect of age and gender


```{r regression distance, echo=FALSE}

mediandata <- data.frame(mediandata)
names(mediandata) <- c('subjectID', 'gender', 'age', 'AQtotal', 'AQsocial', 'AQswitch', 'AQdetail', 'AQcomm', 'AQimag', 'GSQtotal', 'cont_median', 'default_median', 'dorsattn_median', 'limbic_median', 'salventattn_median', 'sommot_median', 'vis_median', 'defaultvis_median_diff')


mod1<-lm(defaultvis_median_diff ~ age + gender + AQsocial + AQswitch + AQdetail + AQcomm + AQimag + GSQtotal, data=mediandata)
summary(mod1)

mod1<-lm(defaultvis_median_diff ~ age + gender + AQtotal + GSQtotal, data=mediandata)
summary(mod1)


mod2<-lm(defaultvis_median_diff ~ AQtotal + GSQtotal, data=mediandata)
summary(mod2)


# compare models
aovtest <- anova(mod2, mod1)
summary(aovtest)

plot(alldata$AQdetail,alldata$simGradient3)
abline(lm(simGradient3~AQdetail, data=alldata))


plot(alldata$GSQtotal,alldata$simGradient3)
abline(lm(simGradient3~GSQtotal, data=alldata))

# type I SS, the restricted model in a regression analysis for your first predictor c is the null-model which only uses the absolute term
summary(manova(mod1)) #Pillai's trace sig for AQdetail, trending for AQimag

#type II SS, the unrestricted model in a regression analysis for your first predictor c is the full model which includes all predictors except for their interaction
Manova(mod1, type="III") #Pillai's trace sig for AQdetail, trending for AQimag

fit<-lm(simGradient1 ~ age + gender + AQsocial + AQswitch + AQdetail + AQcomm + AQimag + GSQtotal, data=alldata)

fit<-lm(simGradient2 ~ age + gender + AQsocial + AQswitch + AQdetail + AQcomm + AQimag + GSQtotal, data=alldata)

fit<-lm(simGradient3 ~ age + gender + AQsocial + AQswitch + AQdetail + AQcomm + AQimag + GSQtotal, data=alldata)


summary(fit)
# Pillai's trace sig for AQdetail -> parameter estimates for these multivariate effects linked to AQdetail for grad 1:3 -> association where error bars do not overlap with zeroconfint(fit, 'body.weight', level=0.95)

confint(fit, 'AQdetail', level=0.9)





```

### schematic metric illustrations


```{r metric illustration, echo=FALSE}


#mock data
g_a <- data.frame(x = rnorm(20, 5, 10), y = rnorm(20, 3, 8), z = rnorm(20, 7, 12))
g_b <- data.frame(x = rnorm(20, 15, 5), y = rnorm(20, -10, 4), z = rnorm(20, -3, 3))

median_a <- g_a %>% dplyr::summarise(across(where(is.numeric), ~ median(.x, na.rm = TRUE)))

median_b <- g_b %>% dplyr::summarise(across(where(is.numeric), ~ median(.x, na.rm = TRUE)))


g_a <- data.frame(g_a, seq(1:20))
median_a_list <- data.frame(median_a[rep(seq_len(nrow(median_a)), each = 20), ], seq(20))
names(median_a_list)[4] <- c("zip")
names(g_a)[4] <- c("zip")

g_a <- bind_rows(g_a, median_a_list) %>% 
           arrange(zip)

g_b <- data.frame(g_b, seq(1:20))
median_b_list <- data.frame(median_b[rep(seq_len(nrow(median_b)), each = 20), ], seq(20))
names(median_b_list)[4] <- c("zip")
names(g_b)[4] <- c("zip")

g_b <- bind_rows(g_b, median_b_list) %>% 
           arrange(zip)


# between-network dispersion
#connecting line for centroids
median_both <- rbind(median_a_list[1,],median_b_list[1,])

scatter3D(
  x=unlist(g_a$x),  y=unlist(g_a$y),  z=unlist(g_a$z),
  xlab=" ", ylab=" ", zlab=" ",
  bty="g", pch=19, cex = 0.6,
  col = c("#af8dc3"))+
scatter3D(
    x=unlist(median_a$x),    y=unlist(median_a$y),    z=unlist(median_a$z),
    add = TRUE, colkey = FALSE,  
    pch = 18, cex = 0.8, col = "black")+
scatter3D(
  x=unlist(g_b$x),  y=unlist(g_b$y),  z=unlist(g_b$z),
  add = TRUE, colkey = FALSE, cex = 0.6,
  pch = 19, col ="#7fbf7b")+
scatter3D(
    x=unlist(median_b$x),    y=unlist(median_b$y),    z=unlist(median_b$z),
    add = TRUE, colkey = FALSE, 
    pch = 18, cex = 0.8, col = "black")+
scatter3D(
    x=unlist(median_both$x),    y=unlist(median_both$y),    z=unlist(median_both$z),
    type="l", lwd=1.8, 
    add = TRUE, colkey = FALSE, 
    pch = 18, cex = 1.5, col = "black")


#eccentricity
#lines to meta-centroid
g_both <- rbind(g_a[seq(1,39, by=2),],g_b[seq(1,39, by=2),])
origin <- data.frame(x=0,y=0,z=0)
origin <- data.frame(origin[rep(seq_len(nrow(origin)), each = 40), ], seq(40))
names(g_both)[4] <- c("zip")
names(origin)[4] <- c("zip")
g_both$zip <- seq(1:40)
g_both <- bind_rows(g_both, origin) %>% 
           arrange(zip)

scatter3D(
  x=unlist(g_a$x),  y=unlist(g_a$y),  z=unlist(g_a$z),
  xlab=" ", ylab=" ", zlab=" ",
  bty="g", pch=19, cex = 0.6,
  col = c("#af8dc3"))+
scatter3D(
  x=unlist(g_b$x),  y=unlist(g_b$y),  z=unlist(g_b$z),
  add = TRUE, colkey = FALSE,  cex = 0.6,
  pch = 19, col ="#7fbf7b")+
scatter3D(
    x=0,    y=0,    z=0,
    add = TRUE, colkey = FALSE, 
    pch = 19, cex = 1.2, col = "black")+
scatter3D(
    x=unlist(g_both[1:40,]$x),    y=unlist(g_both[1:40,]$y),    z=unlist(g_both[1:40,]$z),
    type="l", lwd=1.8,
    add = TRUE, colkey = FALSE, 
    pch = 18, cex = 2, col = "#af8dc3")+
scatter3D(
    x=unlist(g_both[41:80,]$x),    y=unlist(g_both[41:80,]$y),    z=unlist(g_both[41:80,]$z),
    type="l", lwd=1.8,
    add = TRUE, colkey = FALSE, 
    pch = 19, col ="#7fbf7b")


#within-network dispersion
scatter3D(
  x=unlist(g_a$x),  y=unlist(g_a$y),  z=unlist(g_a$z),
  xlab=" ", ylab=" ", zlab=" ",
  bty="g", pch=19,  cex = 0.6,col = c("#af8dc3"))+
scatter3D(
  x=unlist(g_b$x),  y=unlist(g_b$y),  z=unlist(g_b$z),
  add = TRUE, colkey = FALSE, 
  pch = 19, cex = 0.6, col ="#7fbf7b")+
scatter3D(
    x=unlist(g_a$x),    y=unlist(g_a$y),    z=unlist(g_a$z),
    type="l", lwd =1.8,
    add = TRUE, colkey = FALSE,
    pch = 18,  col = "#af8dc3")+
scatter3D(
    x=unlist(g_b$x),    y=unlist(g_b$y),    z=unlist(g_b$z),
    type="l", lwd=1.8,
    add = TRUE, colkey = FALSE,
    pch = 19, col ="#7fbf7b")+
scatter3D(
    x=unlist(median_a$x),    y=unlist(median_a$y),    z=unlist(median_a$z),
    add = TRUE, colkey = FALSE,
    pch = 18, cex = 0.8, col = "black") +
scatter3D(
    x=unlist(median_b$x),    y=unlist(median_b$y),    z=unlist(median_b$z),
    add = TRUE, colkey = FALSE, 
    pch = 18, cex = 0.8, col = "black")




```
